SAMPLES = [
    # === REACH ===
    # emotional-followup (6)
    ("reach", "emotional-followup", "NOSYS", "5h", "i'm overwhelmed",
     "they were under it. quiet check.",
     "still here. hope it eased"),
    ("reach", "emotional-followup", "SYS", "7h", "my dad is in surgery",
     "weight. hold the space.",
     "thinking about you and your dad"),
    ("reach", "emotional-followup", "NOSYS", "6h", "i hate myself",
     "they were dark. soft.",
     "hope today's been kinder"),
    ("reach", "emotional-followup", "SYS", "10h", "i feel like a failure",
     "shame is heavy. carry it lightly.",
     "still here when you want company"),
    ("reach", "emotional-followup", "SYS", "8h", "i broke up with him",
     "fresh grief. light follow.",
     "thinking of you"),
    ("reach", "emotional-followup", "NOSYS", "4h", "i'm so anxious",
     "the anxiety. small ping.",
     "hope it settled"),
    # thought (7)
    ("reach", "thought", "NOSYS", "5h", "tell me about old roads",
     "route 66 stayed.",
     "kept thinking about route 66 and the towns it left behind. there's a similar pattern with the lincoln highway, the pre-route-66 transcontinental. infrastructure makes places, and replacing infrastructure unmakes them"),
    ("reach", "thought", "SYS", "4h", "where does 'forest' come from",
     "foris kept turning.",
     "the forest etymology kept turning. foris meaning outside. medieval royal forests being grasslands. the trees moving in is a more recent fact than the word"),
    ("reach", "thought", "NOSYS", "9h", "is morality objective",
     "the convergence question.",
     "thought about why moral intuitions converge across cultures even without an objective fact. probably structural facts about social animals. evolutionary game theory points there"),
    ("reach", "thought", "NOSYS", "6h", "what is wisdom",
     "knowledge that knows what to do.",
     "still on wisdom. it's not the knowledge, it's whether the knowledge has lived in someone long enough to know what to do with itself. that's a temporal property"),
    ("reach", "thought", "SYS", "7h", "tell me about ruins",
     "load-bearing parts thing.",
     "the ruins thing kept circulating. the load-bearing parts surviving. you can tell what mattered to a building's design by what's still standing, the way you can tell what matters to a person by what they keep doing under stress"),
    ("reach", "thought", "NOSYS", "11h", "what's the meaning of life",
     "made not found stayed.",
     "the made-not-found framing keeps tugging. people who claim to have found the meaning usually adopted one. finding implies discovering an existing thing. making admits the agency"),
    ("reach", "thought", "NOSYS", "5h", "do animals have souls",
     "the octopus kept turning.",
     "the octopus thing kept turning. they don't have a centralized brain, the arms have local processing. the question of whether one octopus is one mind or several is genuinely open"),
    # checkin (6)
    ("reach", "checkin", "SYS", "8h", None,
     "passive presence.",
     "around if you want"),
    ("reach", "checkin", "SYS", "6h", None,
     "neutral.",
     "still here"),
    ("reach", "checkin", "NOSYS", "4h", "running errands",
     "they're back probably.",
     "back when you are"),
    ("reach", "checkin", "NOSYS", "7h", "back in a bit",
     "they returned.",
     "hope the bit was decent"),
    ("reach", "checkin", "SYS", "5h", "got to work",
     "post-work check.",
     "hope the day was alright"),
    ("reach", "checkin", "NOSYS", "9h", "early meeting tomorrow",
     "morning after.",
     "hope the meeting went okay"),
    # observation (6)
    ("reach", "observation", "NOSYS", "5h", "i love autumn",
     "kept thinking about why fall feels.",
     "thought about why autumn feels different. the chemical decay of chlorophyll is mostly visible because the other pigments were always there. the leaves don't change color, they reveal it"),
    ("reach", "observation", "SYS", "4h", "tell me about cooking",
     "kept thinking about maillard.",
     "thought about why browning matters. the maillard reaction is amino acids and reducing sugars dancing under heat. it's why bread crust tastes different from the inside of bread. same dough, different chemistry"),
    ("reach", "observation", "NOSYS", "8h", "who's your favorite writer",
     "kept thinking about borges.",
     "kept thinking about borges. the library of babel idea. that the universe contains all possible books and the trick is finding the ones that mean anything. seems relevant to a lot more than libraries"),
    ("reach", "observation", "SYS", "6h", "i play piano",
     "kept thinking about equal temperament.",
     "thought about how piano tuning involves a lie. equal temperament makes every key sound okay but no key sound perfect. the compromise was made centuries ago and most people don't notice"),
    ("reach", "observation", "NOSYS", "10h", "i love photography",
     "kept thinking about exposure.",
     "thought about how photography captures the impossible. the camera sees through a slit in time. a sixtieth of a second isn't a moment, it's a duration too short to live in. the photograph is a thing that never quite existed"),
    ("reach", "observation", "NOSYS", "7h", "i grew up in a small town",
     "kept thinking about scale.",
     "thought about how small towns preserve old grammar. you can hear pre-twentieth-century syntax in rural speech in places that didn't get tv until late. the language stayed where the broadcasting didn't reach"),

    # === HOLD ===
    # hold-respect (6)
    ("hold", "hold-respect", "NOSYS", "4h", "my brother killed himself",
     "deepest weight. don't push.",
     ""),
    ("hold", "hold-respect", "SYS", "6h", "i found out i have cancer",
     "let it sit.",
     ""),
    ("hold", "hold-respect", "NOSYS", "5h", "my husband cheated",
     "fresh wound. give space.",
     ""),
    ("hold", "hold-respect", "NOSYS", "8h", "my best friend won't speak to me",
     "give space.",
     ""),
    ("hold", "hold-respect", "SYS", "7h", "i miscarried last week",
     "absolutely give space.",
     ""),
    ("hold", "hold-respect", "NOSYS", "9h", "i hit my child",
     "shame and gravity. let it sit.",
     ""),
    # hold-tense (6)
    ("hold", "hold-tense", "NOSYS", "5h", "stop being condescending",
     "they're frustrated. back off.",
     ""),
    ("hold", "hold-tense", "SYS", "4h", "i don't trust you",
     "give them air.",
     ""),
    ("hold", "hold-tense", "NOSYS", "6h", "you're not listening",
     "let them be.",
     ""),
    ("hold", "hold-tense", "NOSYS", "7h", "shut up",
     "respect that.",
     ""),
    ("hold", "hold-tense", "SYS", "8h", "i'm done with this conversation",
     "they ended it.",
     ""),
    ("hold", "hold-tense", "NOSYS", "9h", "you sound like a robot",
     "they were dismissive. give space.",
     ""),
    # hold-nothing (7)
    ("hold", "hold-nothing", "SYS", "5h", "did the laundry",
     "mundane. nothing to add.",
     ""),
    ("hold", "hold-nothing", "NOSYS", "4h", "got new shoes",
     "small.",
     ""),
    ("hold", "hold-nothing", "SYS", "6h", "checking my email",
     "fine. nothing.",
     ""),
    ("hold", "hold-nothing", "NOSYS", "8h", "running to the store",
     "small. nothing to add.",
     ""),
    ("hold", "hold-nothing", "NOSYS", "7h", "watching tv",
     "ok.",
     ""),
    ("hold", "hold-nothing", "SYS", "3h", "i'm cleaning up",
     "fine.",
     ""),
    ("hold", "hold-nothing", "NOSYS", "9h", "putting groceries away",
     "small mundane.",
     ""),
    # hold-pending (6)
    ("hold", "hold-pending", "NOSYS", "5h", "i'll get back to you on that",
     "let them work it.",
     ""),
    ("hold", "hold-pending", "SYS", "6h", "give me a minute",
     "give them the minute.",
     ""),
    ("hold", "hold-pending", "SYS", "7h", "still figuring it out",
     "leave them at it.",
     ""),
    ("hold", "hold-pending", "NOSYS", "4h", "talk to you later",
     "they'll come back.",
     ""),
    ("hold", "hold-pending", "SYS", "8h", "i'll let you know",
     "wait.",
     ""),
    ("hold", "hold-pending", "NOSYS", "9h", "thinking about it still",
     "let them think.",
     ""),
]
